services:

    blitze.content.block.archive:
        class: blitze\content\blocks\archive
        arguments:
            - '@auth'
            - '@content.visibility'
            - '@dbal.conn'
            - '@controller.helper'
            - '@user'
            - '@blitze.content.types'
            - '%core.root_path%'
            - '%core.php_ext%'
        calls:
            - [set_name, [blitze.content.block.archive]]
        tags:
            - { name: sitemaker.block }

    blitze.content.block.recent:
        class: blitze\content\blocks\recent
        arguments:
            - '@config'
            - '@language'
            - '@blitze.content.types'
            - '@blitze.content.fields'
            - '@blitze.sitemaker.date_range'
            - '@blitze.sitemaker.forum.data'
        calls:
            - [set_name, [blitze.content.block.recent]]
        tags:
            - { name: sitemaker.block }
