services:

    blitze.content.block.archive:
        class: blitze\content\blocks\archive
        arguments:
            - @auth
            - @content.visibility
            - @dbal.conn
            - @controller.helper
            - @user
            - @blitze.content.types
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [blitze.content.block.archive]]
        tags:
            - { name: sitemaker.block }

    blitze.content.block.calendr:
        class: blitze\content\blocks\calendr
        arguments:
            - @config
            - @user
            - @blitze.content.displayer
            - @blitze.sitemaker.forum.data
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [blitze.content.block.calendar]]
        tags:
            - { name: sitemaker.block }

    blitze.content.block.recent:
        class: blitze\content\blocks\recent
        arguments:
            - @config
            - @user
            - @blitze.content.displayer
            - @blitze.sitemaker.date_range
            - @blitze.sitemaker.forum.data
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [blitze.content.block.recent]]
        tags:
            - { name: sitemaker.block }