services:

    primetime.content.block.archive:
        class: primetime\content\blocks\archive
        arguments:
            - @auth
            - @content.visibility
            - @dbal.conn
            - @controller.helper
            - @user
            - @primetime.content.types
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.content.block.archive]]
        tags:
            - { name: primetime.block }

    primetime.content.block.calendr:
        class: primetime\content\blocks\calendr
        arguments:
            - @config
            - @user
            - @primetime.content.displayer
            - @primetime.core.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.content.block.calendar]]
        tags:
            - { name: primetime.block }

    primetime.content.block.recent:
        class: primetime\content\blocks\recent
        arguments:
            - @config
            - @user
            - @primetime.content.displayer
            - @primetime.core.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.content.block.recent]]
        tags:
            - { name: primetime.block }