services:
    blitze.content.template.twig.environment:
        class: phpbb\template\twig\environment
        arguments:
            - '@config'
            - '@filesystem'
            - '@path_helper'
            - '%core.template.cache_path%'
            - '@ext.manager'
            - '@blitze.content.template_loader'
            - []
        calls:
            - [setLexer, ['@template.twig.lexer']]

    blitze.content.template_loader:
        class: blitze\content\services\template_loader
        arguments:
            - '@blitze.content.types'
            - '@blitze.sitemaker.mapper.factory'

    blitze.content.template:
        class: phpbb\template\twig\twig
        arguments:
            - '@path_helper'
            - '@config'
            - '@template_context'
            - '@blitze.content.template.twig.environment'
            - '%core.template.cache_path%'
            - '@user'
            - '@template.twig.extensions.collection'
            - '@ext.manager'