services:

    blitze.content.view.blog:
        class: blitze\content\services\views\blog
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user
            - @blitze.content.displayer
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: content.view }

    blitze.content.view.portal:
        class: blitze\content\services\views\portal
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user
            - @blitze.content.displayer
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: content.view }

    blitze.content.view.tiles:
        class: blitze\content\services\views\tiles
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @blitze.content.displayer
            - @blitze.sitemaker.util
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: content.view }