services:

    blitze.content.view.blog:
        class: blitze\content\services\views\blog
        arguments:
            - '@language'
            - '@pagination'
            - '@template'
            - '@blitze.content.fields'
            - '@blitze.sitemaker.forum.data'
            - '@blitze.content.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: sitemaker.content.view }

    blitze.content.view.portal:
        class: blitze\content\services\views\portal
        arguments:
            - '@language'
            - '@pagination'
            - '@template'
            - '@blitze.content.fields'
            - '@blitze.sitemaker.forum.data'
            - '@blitze.content.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: sitemaker.content.view }

    blitze.content.view.tiles:
        class: blitze\content\services\views\tiles
        arguments:
            - '@language'
            - '@pagination'
            - '@request'
            - '@template'
            - '@blitze.content.fields'
            - '@blitze.sitemaker.forum.data'
            - '@blitze.content.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: sitemaker.content.view }
